# MQTT configuration
mqtt:
  broker: "tcp://localhost:1883"
  client_id: "data-trans-client"
  username: "user"
  password: "password"
  topics:
    - "devices/temperature/+"
    - "devices/humidity/+"
# Logging configuration
logger:
  level: "DEBUG"       # Log level: DEBUG, INFO, WARN, ERROR
  file_path: "./logs/app.log"  # Log file path
  max_size: 10        # Single log file maximum size (MB)
  max_backups: 5      # Maximum number of log files to retain
  console: true       # Whether to log to the console
# Storage configuration
storage:
  # File storage
  file:
    enabled: true
    path: "./data"
  # Database storage
  database:
    enabled: true
    # Database type: mysql or postgresql
    type: "mysql"
    # MySQL connection string example: user:password@tcp(localhost:3306)/data_trans
    # PostgreSQL connection string example: postgres://user:password@localhost:5432/data_trans?sslmode=disable
    dsn: "user:password@tcp(localhost:3306)/data_trans"
# Transformer configuration
transformers:
  # Temperature sensor transformer
  temperature:
    script_path: "./scripts/temperature.js"
  
  # Humidity sensor transformer
  humidity:
    script_path: "./scripts/humidity.js"